// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4uTg49PkMUwaVVX1EkPpDMZHjr3Vk0yI',
    appId: '1:1072375362444:web:fd1f3d00cfd24e6fbedca9',
    messagingSenderId: '1072375362444',
    projectId: 'cimema-sync',
    authDomain: 'cimema-sync.firebaseapp.com',
    storageBucket: 'cimema-sync.appspot.com',
    measurementId: 'G-RM2SSHVTP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMXfkdkz5WFoOrFxtHGXJDFgYtO4yGTio',
    appId: '1:1072375362444:android:7501d2956e07df90bedca9',
    messagingSenderId: '1072375362444',
    projectId: 'cimema-sync',
    storageBucket: 'cimema-sync.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYqd1tH6xQfhHgOkoW0QPxIUB4WHVoJ0I',
    appId: '1:1072375362444:ios:e98e89843c00741ebedca9',
    messagingSenderId: '1072375362444',
    projectId: 'cimema-sync',
    storageBucket: 'cimema-sync.appspot.com',
    iosBundleId: 'com.example.cinemaSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYqd1tH6xQfhHgOkoW0QPxIUB4WHVoJ0I',
    appId: '1:1072375362444:ios:4d579d3feb6b84eebedca9',
    messagingSenderId: '1072375362444',
    projectId: 'cimema-sync',
    storageBucket: 'cimema-sync.appspot.com',
    iosBundleId: 'com.example.cinemaSync.RunnerTests',
  );
}
